"""
Importer stage of the exercise import pipeline.

Takes the validator's output and generates SQL that:
  - seeds the reference tables (exercise_categories, muscle_groups,
    equipment) with the real taxonomy values this dataset uses
  - inserts every exercise, its images, and its muscle/equipment
    relationships

All INSERTs use ON CONFLICT DO NOTHING / DO UPDATE so this script is
safe to re-run against a database that already has some or all of this
data (idempotent import, not "run once or corrupt your data").

Run: python3 generate_sql.py
Reads:  ../validator/validated_exercises.json
Writes: ../../seed/02_exercise_library.sql
"""
import json
from pathlib import Path

IN_PATH = Path(__file__).parent.parent / "validator" / "validated_exercises.json"
OUT_PATH = Path(__file__).parent.parent.parent / "seed" / "02_exercise_library.sql"

CATEGORY_DESCRIPTIONS = {
    "strength": "Traditional resistance training exercises",
    "cardio": "Cardiovascular/endurance exercises",
    "stretching": "Flexibility and mobility exercises",
    "plyometrics": "Explosive, jump-based training",
    "powerlifting": "Squat, bench, deadlift and their variations",
    "olympic weightlifting": "Snatch, clean & jerk and their variations",
    "strongman": "Strongman-style functional strength movements",
}

MUSCLE_BODY_REGION = {
    "quadriceps": "lower_body", "hamstrings": "lower_body", "calves": "lower_body",
    "glutes": "lower_body", "adductors": "lower_body", "abductors": "lower_body",
    "shoulders": "upper_body", "chest": "upper_body", "triceps": "upper_body",
    "biceps": "upper_body", "lats": "upper_body", "middle back": "upper_body",
    "forearms": "upper_body", "traps": "upper_body", "neck": "upper_body",
    "abdominals": "core", "lower back": "core",
}


def esc(s):
    """Escape a value for a SQL string literal, or return NULL."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def esc_array(items):
    if not items:
        return "'{}'"
    escaped = [esc(i) for i in items]
    return "ARRAY[" + ", ".join(escaped) + "]::text[]"


def main():
    records = json.loads(IN_PATH.read_text())

    lines = [
        "-- Generated by exercise_import/importer/generate_sql.py — do not hand-edit.",
        "-- Regenerate by re-running the transform -> validate -> generate_sql pipeline.",
        "-- Source: free-exercise-db (public domain), github.com/yuhonas/free-exercise-db",
        "",
        "-- ============ Reference data ============",
        "",
    ]

    # exercise_categories
    for cat, rank in zip(CATEGORY_DESCRIPTIONS, range(len(CATEGORY_DESCRIPTIONS))):
        lines.append(
            f"insert into public.exercise_categories (name, description, display_order) "
            f"values ({esc(cat)}, {esc(CATEGORY_DESCRIPTIONS[cat])}, {rank}) "
            f"on conflict (name) do nothing;"
        )
    lines.append("")

    # muscle_groups
    for i, (muscle, region) in enumerate(MUSCLE_BODY_REGION.items()):
        lines.append(
            f"insert into public.muscle_groups (name, body_region, display_order) "
            f"values ({esc(muscle)}, {esc(region)}, {i}) "
            f"on conflict (name) do nothing;"
        )
    lines.append("")

    # equipment — collect distinct (name, category) pairs actually used
    equipment_seen = {}
    for r in records:
        equipment_seen[r["equipment_name"]] = r["equipment_category"]
    for i, (name, category) in enumerate(sorted(equipment_seen.items())):
        lines.append(
            f"insert into public.equipment (name, equipment_category, display_order) "
            f"values ({esc(name)}, {esc(category)}, {i}) "
            f"on conflict (name) do nothing;"
        )
    lines.append("")
    lines.append("-- ============ Exercises ============")
    lines.append("")

    for r in records:
        lines.append("do $$")
        lines.append("declare v_exercise_id uuid; v_category_id uuid;")
        lines.append("begin")
        lines.append(f"  select id into v_category_id from public.exercise_categories where name = {esc(r['category'])};")
        lines.append(
            "  insert into public.exercises "
            "(name, slug, description, category_id, exercise_type, mechanics, force, difficulty, instructions) "
            "values ("
            f"{esc(r['name'])}, {esc(r['slug'])}, {esc(r['description'])}, v_category_id, "
            f"{esc(r['exercise_type'])}, {esc(r['mechanics'])}, {esc(r['force'])}, {esc(r['difficulty'])}, "
            f"{esc_array(r['instructions'])}"
            ") on conflict (slug) do nothing "
            "returning id into v_exercise_id;"
        )
        lines.append("  if v_exercise_id is null then")
        lines.append(f"    select id into v_exercise_id from public.exercises where slug = {esc(r['slug'])};")
        lines.append("  end if;")

        for muscle in r["primary_muscles"]:
            lines.append(
                f"  insert into public.exercise_muscles (exercise_id, muscle_group_id, role) "
                f"select v_exercise_id, id, 'primary' from public.muscle_groups where name = {esc(muscle)} "
                f"on conflict do nothing;"
            )
        for muscle in r["secondary_muscles"]:
            lines.append(
                f"  insert into public.exercise_muscles (exercise_id, muscle_group_id, role) "
                f"select v_exercise_id, id, 'secondary' from public.muscle_groups where name = {esc(muscle)} "
                f"on conflict do nothing;"
            )

        lines.append(
            f"  insert into public.exercise_equipment (exercise_id, equipment_id) "
            f"select v_exercise_id, id from public.equipment where name = {esc(r['equipment_name'])} "
            f"on conflict do nothing;"
        )

        for i, img in enumerate(r["images"]):
            lines.append(
                f"  insert into public.exercise_images (exercise_id, url, display_order) "
                f"values (v_exercise_id, {esc(img)}, {i});"
            )

        lines.append("end $$;")
        lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {OUT_PATH} ({len(records)} exercises, {sum(len(r['images']) for r in records)} images)")


if __name__ == "__main__":
    main()
